#+STARTUP: showall indent
#+STARTUP: hidestars
#+OPTIONS: H:2 num:nil tags:nil toc:nil timestamps:nil
#+TITLE: Trip to Chamonix 2011.
#+BEGIN_HTML
---
layout:  mountaineering
title: Trip to Chamonix 2011.
comments: true
categories: [mountaineering]
---
#+END_HTML

* Our Trip to Chamonix 2011.
I think I first went to Chamonix in 1977 with a couple of friends from
University, when we failed to climb Mont Blanc. From about 1980 to
1987 I went almost every summer, managing to climb several of the
classic routes in the range. In those days we used to camp in Snell's
Field, or Pierre d'Orthaz opposite which were the spiritual home of
British Alpinists. My last trip to Chamonix was about 1993.

Chamonix is an unusual place. Down in the valley, it's an expensive
resort with many tourist attractions. However, if you ride up on the
Midi telepherique and step out of the tunnel onto the start of the
Midi-Plan arete, you are suddenly transferred into the stark world of
granite and ice that make up the mountains. Similarly if you ride the
rack railway up to Montenvers and climb down onto the Mer de Glace you
are surrounded by mountains like the Dru and the Grandes Jorasses,
that have inspired generations of climbers.

Most routes require a day to reach a hut. next morning the obligatory
early "Alpine Start" in the early hours to reach your summit and
return to the hut before the snow melts and the stone fall starts,
followed by a long tired trudge back to the valley. In those hours
between leaving the hut and returning from your climb, you will
probably feel very cold, then later much too hot. Until you achieve
the required level of fitness, you will feel tired. Often, although
the climbing will not be too hard, the need for speed means that you
are effectively soloing, with the consequences of an accidental slip
all too obvious.

Once back in the valley, exhausted and with sore feet you will vow
never to return. However, after a few beers and a couple of days rest
you will feel the pull of the mountains again and will once again be
plodding up towards a hut. Your ambitions will increase and the
"Grandes Courses" like the Brenva Face climbs will be on your
list. It's too late you have now become addicted.


