#+STARTUP: showall indent
#+STARTUP: hidestars
#+OPTIONS: H:2 num:nil tags:nil toc:nil timestamps:nil
#+BEGIN_HTML
Title: Coast To Coast Cycle Ride Day Two.
Date: 2014-08-13
Tags: [cycling]
Status: draft
Category: blog

#+END_HTML

* Penrith to Allenheads.
We had originally planned this section to complete the major climbs of
the middle section in one day. It turned out to be a very short day,
about three and a half hours. In retrospect it would have been better
to continue beyond Allenheads, but as we had pre-booked accomodation
this wasn't possible. With a bit more planning we could have probably
completed the route in two days, although for me, this would have been
pushing it a bit.

We had arranged to meet my son and his friends at the place they were
staying in Penrith about 8:30am. We had planned to have breakfast at
the Little Chef, but although the pillar on the outside said it would
open at 7:00am, it turned out that it wouldn't in fact open until
8:00am. Somewhat fed up, I decided to cycle down into Penrith and have
breakfast at Morrisons. After breakfast, I cycled up the steep hill to
the house where my son was staying. The house was actually on the C2C,
which made initial route finding straightforward.

My son and his friends raced off in front while my brother in law and
myself followed at a more sedate pace. Once again the weather looked
decidedly dodgy, with cloud obscuring the moors in front of us. We
passed through Langwathby . There followed several sections of up and
down, but nothing too steep. We could see cars climbing the A686, high
up on the moors, in
the distance. The tops were covered in cloud, so we couldn't see that
cafe.

From the description I had expected the hill up to Hartside to be
challenging. However, it turned out to be much easier than many of the
other lesser hills. It's long, but apart from a very short section,
where the route joins the main A686, it's not particularly steep. I
managed to maintain a respectable pace and only stopped to take
photos. I arrived at the cafe just as the cloud lifted. I couldn't
have timed it better. The cafe wasn't too busy and a couple of cups of
tea with an apricot slice were very welcome.

The descent from the cafe was very pleasant. Although it's on an A
road, there was very little traffic. Not having seen any traffic for
the last three miles, as soon as I wanted to turn right at Leadgate a veritable
convoy suddenly appeared behind me. The ride down into Garigill was
pleasant. However, the intial section was a shocker. After overcoming
this initial very steep part, the hill goes on, and on, and on. The
subsequent sections aren't too steep and there are fine views all
around. We stopped for a drink and some food at the top of the hill
before beginning the descent towards Nenthead. Just before arriving at
Nenthead there is a very steep descent. This culminates in a couple of
very sharp bends and the road is very potholed. There are several
signs warning you to slow down. Take note! Going too fast will result
in a painful crash.

My wife was waiting at Nenthead and we stopped for a chat and some
more to drink.  After an initial steep climb out of the village we
turned off along the B road to climb up to the top of Black Hill, the
highest point of the C2C. There follows a short descent before another
small hill. After that it's a great downhill ride all the way to
Allenheads.

The village of Allenheads is quite stretched out and the pub and our
accommodation were at the far end. My son and his friends stayed in
the pub,  ee stayed at [[http://www.allenheadsc2c.com][Newhouses]], which was a
short way out of the village up a track. The proprietor seemed very
confused about exactly who she had booked in, despite email
confirmations. However, we sorted it out eventually. The accommodation
was superb. The rooms were large and comfortable. Downstairs there was
a separate residents lounge and kitchen.

After a short rest, we wandered down into the village to join the
others at the pub. We had an enjoyable meal and a few drinks before
wandering back up the road to our beds.
