#+STARTUP: showall indent
#+STARTUP: hidestars
#+OPTIONS: H:2 num:nil tags:nil toc:nil timestamps:nil
#+TITLE: Moel Siabod.
#+BEGIN_HTML
--- 
layout:  mountaineering
title: Moel Siabod.
--- 
#+END_HTML
Moel Siabod is one of my favourite mountains. Many years ago we often
spent family holidays staying at Cobdens Hotel in Capel
Curig. Although we never climbed to the summit of Moel Siabod, we
spent many days walking on it's flanks.

Since Moel Siabod is relatively isolated, there are extensive views
over Snowdonia from the summit. There are a number of possible routes
to the summit. My favourite starts at Pont Cyfyng in Capel Curig and
incorporates a classic easy scramble up the South East Ridge.

There is limited parking in a layby on the A5 just outside Capel Curig
and also a small car park next to the Bryn Glo cafe. From the car park
cross the bridge, taking time to have a look at the Cyfyng falls,
which are interesting especially after heavy rain. Walk down the road
for a few hundred yards and take the farm track on the right, which
rises steeply. In years gone by the path followed the track up past
the farm. However, there is now a well signposted diversion which
circumvents the buildings, rejoining the track higher up.

Follow the track over the moor to the point where it ends at a
style. The track now branches with the left hand branch leading up
towards Lyn y Foel and the other branch going straight on up the south
eastern ridge towards the summit.

I think that the best way up to the summit is the scramble up the
Ddear Ddu Ridge. To get to the bottom of the ridge take the left hand
path from the ladder style at the end of the farm track. This winds
uphill past some old mine workings and a flooded pit. Finally you
climb over a shoulder to reach Llyn y Foel and you can see the Ddear Ddu
Ridge rising up beyond the far end of the lake. Cross the wet ground
near to the lake to gain the foot of the ridge. If it looks very wet
you can skirt the right hand side of the lake. 

However, don't be tempted to take the path higher up the hillside
above the lake. If you follow the higher path, you can't climb onto
the ridge without losing a lot of height first. If for some reason you
do go this way it is possible to continue following the path steeply
up a penitential scree gully to emerge just below the summit.

Once past Llyn y Foel gain the Ddear Ddu Ridge near its lowest
point. The best scrambling is along the crest. However, almost all
difficulties can be turned. The ridge emerges right next to the summit
cairn.

There are various alternatives for descent. You can walk along the
crest of the whale back north east ridge. There is also a path that
follows the grass slope just below the ridge. At the end of the ridge
the path descends to the south east back to the ladder stile at the
end of the farm track. The way down is fairly obvious even in mist.

Alternatively you can follow a path that leads from the summit stone
shelter down to the north east, over grassy slopes and through the
forest, to reach Plas y Brenin. From the river you can follow forestry
paths along the southern bank finally crossing the river at a green
bridge opposite to Cobdens Hotel in Capel Curig.

